#!/usr/bin/env zsh

if ! pgrep picom > /dev/null; then
	feh --bg-fill ~/.config/bspwm/bg.jpg

	picom &

	~/.config/C_Bar/C_Bar &

	qbittorrent &

	ciadpi -d 2 &

	ciadpi -p 1081 -o 1 &

	nekobox -tray &

	sxhkd &
fi

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc rule -a firefox-nightly state=tiled

bspc rule -a firefox-nightly:Alert state=floating

bspc rule -a firefox-nightly:Browser state=floating

bspc rule -a firefox-nightly:Firefox state=floating border=off

bspc rule -a matplotlib state=floating

. "${HOME}/.cache/wal/colors.sh"

bspc config normal_border_color "$color1"

bspc config active_border_color "$color1"

bspc config focused_border_color "$color7"

bspc config presel_feedback_color "$color1"

bspc config click_to_focus any

bspc config window_gap 32

bspc config border_width 1
