#!/bin/zsh

if ! pgrep picom > /dev/null; then
	feh --bg-fill ~/.config/bspwm/bg.jpg

	picom &

	pkill -x C_Bar

	~/.config/C_Bar/C_Bar &

	qbittorrent &

	sxhkd &
fi

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc rule -a firefox-nightly state=tiled

bspc rule -a firefox-nightly:Alert state=floating

. "${HOME}/.cache/wal/colors.sh"

bspc config normal_border_color "$color1"

bspc config active_border_color "$color1"

bspc config focused_border_color "$color7"

bspc config presel_feedback_color "$color1"

bspc config click_to_focus any

bspc config window_gap 32

bspc config border_width 1
